{"cells":[{"source":"<a href=\"https://www.kaggle.com/luisprezsala/batman?scriptVersionId=89605270\" target=\"_blank\"><img align=\"left\" alt=\"Kaggle\" title=\"Open in Kaggle\" src=\"https://kaggle.com/static/images/open-in-kaggle.svg\"></a>","metadata":{},"cell_type":"markdown","outputs":[],"execution_count":0},{"cell_type":"code","execution_count":null,"id":"95b92542","metadata":{"papermill":{"duration":0.004622,"end_time":"2022-03-08T18:41:43.067808","exception":false,"start_time":"2022-03-08T18:41:43.063186","status":"completed"},"tags":[]},"outputs":[],"source":[]},{"cell_type":"raw","id":"bf582893","metadata":{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","papermill":{"duration":0.002701,"end_time":"2022-03-08T18:41:43.073924","exception":false,"start_time":"2022-03-08T18:41:43.071223","status":"completed"},"tags":[]},"source":["# This Python 3 environment comes with many helpful analytics libraries installed\n","# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n","# For example, here's several helpful packages to load\n","\n","import numpy as np # linear algebra\n","import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n","\n","# Input data files are available in the read-only \"../input/\" directory\n","# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n","\n","import os\n","for dirname, _, filenames in os.walk('/kaggle/input'):\n","    for filename in filenames:\n","        print(os.path.join(dirname, filename))\n","\n","# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n","# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session"]},{"cell_type":"code","execution_count":1,"id":"c62bfdbd","metadata":{"execution":{"iopub.execute_input":"2022-03-08T18:41:43.086634Z","iopub.status.busy":"2022-03-08T18:41:43.08506Z","iopub.status.idle":"2022-03-08T18:44:13.006464Z","shell.execute_reply":"2022-03-08T18:44:13.005718Z"},"papermill":{"duration":149.929216,"end_time":"2022-03-08T18:44:13.006638","exception":false,"start_time":"2022-03-08T18:41:43.077422","status":"completed"},"tags":[]},"outputs":[{"name":"stdout","output_type":"stream","text":["\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ffc4fac50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pysubgroup/\u001b[0m\r\n","\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ffc4faf90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pysubgroup/\u001b[0m\r\n","\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ffc511310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pysubgroup/\u001b[0m\r\n","\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ffc511650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pysubgroup/\u001b[0m\r\n","\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ffc511990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pysubgroup/\u001b[0m\r\n","\u001b[31mERROR: Could not find a version that satisfies the requirement pysubgroup (from versions: none)\u001b[0m\r\n","\u001b[31mERROR: No matching distribution found for pysubgroup\u001b[0m\r\n","Note: you may need to restart the kernel to use updated packages.\n"]}],"source":["pip install pysubgroup"]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.12"},"papermill":{"default_parameters":{},"duration":159.514874,"end_time":"2022-03-08T18:44:13.7229","environment_variables":{},"exception":null,"input_path":"__notebook__.ipynb","output_path":"__notebook__.ipynb","parameters":{},"start_time":"2022-03-08T18:41:34.208026","version":"2.3.3"}},"nbformat":4,"nbformat_minor":5}